---
- name: Create download directories
  file:
    path: "{{ temp_directory }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwx,g=rwx,o=rx

- name: Create file generation script
  template:
    src: create-test-files.sh.j2
    dest: "{{ file_generation_script }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwx,g=rwx,o=rx
 
- name: Create torrent data files
  command:
    cmd: "{{ file_generation_script }}"
    creates: "{{ temp_directory }}/zero"
  become: yes
  become_user: "{{ user }}"
