---
  - name: Install gnupg2 for adding PPA
    apt:
      name: gnupg2
      cache_valid_time: "{{ apt_cache_valid_time }}"

  - name: Add qBittorrent PPA
    apt_repository:
      repo: ppa:qbittorrent-team/qbittorrent-stable
      state: present

  - name: Install packages
    apt:
      name: qbittorrent
      cache_valid_time: "{{ apt_cache_valid_time }}"

  - name: Create qbittorrent user
    user:
      name: "{{ user }}"
      comment: "Bittorrent service"
  
  - name: Create qBittorrent configuration directory
    file:
      path: /home/qbittorrent/.config/qBittorrent/
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: u=rwx,g=rwx,o=

  - name: Copy qBittorrent configuration
    template:
      src: qBittorrent.conf.j2
      dest: /home/qbittorrent/.config/qBittorrent/qBittorrent.conf

  - name: Create qBittorrent systemd unit
    template:
      src: qbittorrent.service.j2
      dest: /etc/systemd/system/qbittorrent.service
      group: root
      owner: root

  - name: Enable and start qBittorrent service
    systemd:
      name: qbittorrent
      daemon_reload: yes
      enabled: yes
      state: started

